rbenv_install_dir : /home/vagrant/.rbenv
ruby_build_install_dir : /home/vagrant/.rbenv/plugins/ruby-build
rbenv_install_user_dir : /home/vagrant
document_root: /home/vagrant/rails5-api-prototype/public
domain_name: dev.rails5-api.net
