- name: create database {{ mysql_db_name }}
  mysql_db:
    name: "{{ mysql_db_name }}"
    login_password: "{{ mysql_root_password }}"
    state: present

- name: create database {{ mysql_test_db_name }}
  mysql_db:
    name: "{{ mysql_test_db_name }}"
    login_password: "{{ mysql_root_password }}"
    state: present

- name: create {{ mysql_db_user }}
  mysql_user: name={{ mysql_db_user }} login_password={{ mysql_root_password }} host={{ item }} password={{ mysql_user_password }} priv={{ mysql_db_name }}.*:ALL state=present
  with_items:
    - 127.0.0.1
    - localhost
    - 192.168.%

- name: create {{ mysql_test_db_user }}
  mysql_user: name={{ mysql_test_db_user }} login_password={{ mysql_root_password }} host={{ item }} password={{ mysql_user_password }} priv={{ mysql_test_db_name }}.*:ALL state=present
  with_items:
    - 127.0.0.1
    - localhost
    - 192.168.%
