- name: install MySQL-python for ansible mysql_user module
  yum: name=MySQL-python state=installed

- name: tmp root password
  shell: cat /var/log/mysqld.log | grep password | awk '{ print $NF }' | head -n 1
  register: mysql_tmp_password

- name: check mysql root password
  command: mysqlshow -uroot -p'{{ mysql_tmp_password.stdout }}'
  register: root_check
  changed_when: no
  ignore_errors: yes

- name: set mysql root password
  command: mysql --connect-expired-password -uroot -p'{{ mysql_tmp_password.stdout }}' -e "set password for root@'localhost' = PASSWORD('{{ mysql_root_password }}')"
  when: root_check.stderr.find('denied') == -1
